<a href="https://colab.research.google.com/github/adnansherwani/Deep-Learning/blob/main/00__pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

*   Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
*   Documents:  https://pytorch.org/docs/stable/index.html

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
print(torch.__version__)

2.4.1+cu121


In [ ]:
torch.cuda.is_available()

True

In [ ]:
!nvidia-smi

Sun Sep 29 13:35:13 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   57C    P8               9W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to tensors
  
  ### Creating Tensors

  PyTorch Tensors are created using torch.Tensor() - https://pytorch.org/docs/stable/tensors.html


In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Getting the python tensor as int
scalar.item()

7

In [ ]:
# Vector
vector = torch.tensor(data=[1, 2])
vector

tensor([1, 2])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
MATRIX = torch.tensor(data=[[2,4],
                            [6,7]])
MATRIX

tensor([[2, 4],
        [6, 7]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([6, 7])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
TENSOR = torch.tensor(data=[[[[9,4,6],
                             [4,7,4],
                             [8,4,7]],
                            [[3,5,6],
                            [5,7,9],
                            [1,8,0]]],
                            [[[2,4,5],
                             [4,5,6],
                             [6,7,5]],
                            [[3,4,6],
                             [3,5,6],
                             [5,3,4]]],
                            [[[1,4,5],
                             [4,7,6],
                             [9,7,4]],
                             [[3,5,7],
                              [6,8,3],
                              [7,7,5]]]])

In [ ]:
TENSOR

tensor([[[[9, 4, 6],
          [4, 7, 4],
          [8, 4, 7]],

         [[3, 5, 6],
          [5, 7, 9],
          [1, 8, 0]]],


        [[[2, 4, 5],
          [4, 5, 6],
          [6, 7, 5]],

         [[3, 4, 6],
          [3, 5, 6],
          [5, 3, 4]]],


        [[[1, 4, 5],
          [4, 7, 6],
          [9, 7, 4]],

         [[3, 5, 7],
          [6, 8, 3],
          [7, 7, 5]]]])

In [ ]:
TENSOR.ndim

4

In [ ]:
TENSOR.shape

torch.Size([3, 2, 3, 3])

In [ ]:
TENSOR[0][1][0][1]

tensor(5)

In [ ]:
TENSOR_1 = torch.randint(low=0, high=9, size=(3,3,3,3,3))

In [ ]:
TENSOR_1.item

<function Tensor.item>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they stary with a tensor full of random numbers and then adjust those randome number to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random number`

Torch Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [ ]:
### Create a random tensor of size or shape (3,4)

rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.3175, 0.7162, 0.8773],
        [0.0146, 0.0061, 0.8097],
        [0.1025, 0.4875, 0.3401],
        [0.5945, 0.3915, 0.7387]])

In [ ]:
rand_tensor.ndim

2

In [ ]:
## Create a random tensor with similar shape to an image tensor

rand_image_s_tensor = torch.rand(size=(224, 224, 3)) ## height, width. color channels (RGB)
rand_image_s_tensor.shape, rand_image_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones tensors

In [ ]:
# Create a tensor of all zeros & ones

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

### Create a range of tensors and tensors like

In [ ]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1, dtype= None)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=rand_tensor[1][0])
ten_zeros

tensor(0.)

In [ ]:
rand_tensor*ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor Data Types

**Note:** Tensor datatypes is one of the 3 big errors you'll face with Pytorch or datatypes.

  1. Tensors not right datatype.
  2. Tensors not right shape
  3. Tensors not on the right device

Tensor Datatypes: https://pytorch.org/docs/stable/tensors.html

Precision Computer science : https://dbpedia.org/page/Precision_(computer_science)

In [ ]:
# float 32 tensor
float32_tensor = torch.tensor(data=[3.0, 6.0, 9.0],
                              dtype=None,    #what datatypes is the tensor (e.g float)
                              device=None,  # what device is the tensor on cpu or cuda
                              requires_grad=False)   #whether or not to track gradients
float32_tensor

tensor([3., 6., 9.])

In [ ]:
float32_tensor.dtype

torch.float32

In [ ]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
((float32_tensor * float16_tensor * float32_tensor) + float32_tensor / float16_tensor).shape

torch.Size([3])

### Getting Information from Tensor.

  1. Tensors not right datatype - use `tensor.dtype`
  2. Tensors not right shape - use `tensor.shape`
  3. Tensors not on the right device - use `tensor.device`



In [ ]:
## Create random tensors.
some_tensors = torch.rand(size=(2,3,3), dtype=torch.float16, device='cpu')

In [ ]:
# Details of some_random tensors.

print(some_tensors)
print(f"Datatype :{some_tensors.dtype}")
print(f"Shape :{some_tensors.shape}")
print(f"Device :{some_tensors.device}")


tensor([[[0.3208, 0.8564, 0.7231],
         [0.9004, 0.8550, 0.7490],
         [0.5781, 0.5391, 0.1953]],

        [[0.7070, 0.7690, 0.8662],
         [0.9707, 0.6221, 0.4678],
         [0.6772, 0.6382, 0.9980]]], dtype=torch.float16)
Datatype :torch.float16
Shape :torch.Size([2, 3, 3])
Device :cpu


### Manipulating Tensors (tensor operations)

Tensors operation includes:
 1. Addition
 2. Substraction
 3. Multiplication (element-wise)
 4.  Division
 5. Matrix Multiplication

In [ ]:
# Create a tensor

tensor = torch.tensor(data=[2,4,6])
tensor + 3 #addition

tensor([5, 7, 9])

In [ ]:
tensor * 10 # Mulitplication

tensor([20, 40, 60])

In [ ]:
tensor - 10 # Subtractions

tensor([-8, -6, -4])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks & deep learning.

1. Element-wise
2. Matrix Multiplication (dot product)

More information: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**Note :** There are two main rules that performing matrix multiplication needs to satisfy:

1.   The **inner dimensions** must match:

  *   `(3, 2) * (3, 2)` won't work
  *   `(2, 3) * (3, 2)` will work
  *   `(3, 2) * (2, 3)` will work

2.   The resulting matrix has the shape of the **outer dimensions:**

  *   `(2, 3) * (3, 2)` -> shape `(2, 2)`
  *   `(3, 2) * (2, 3)` -> shape  `(3, 3)`


**Important :** For Matrix Multiplication, we have different alias for torch.matmul() such as
  1. torch.mm
  2. `@`







In [ ]:
# Element wise multiplication

print(tensor*tensor)

tensor([ 4, 16, 36])


In [ ]:
# Matrix Maultiplication

print(tensor, "*", tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])


In [ ]:
torch.matmul(input=tensor, other=tensor)

tensor(56)

In [ ]:
2*2 + 4*4+6*6

56

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(56)
CPU times: user 2.3 ms, sys: 0 ns, total: 2.3 ms
Wall time: 2.66 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 6 µs, total: 40 µs
Wall time: 42.9 µs


tensor(56)

### One of the most common errors in deep learning:  shape errors

In [ ]:
# shapes for matrix multiplication

tensor_A  = torch.randint(low=1, high=10, size=(4, 3))
tensor_A

tensor([[3, 1, 3],
        [7, 2, 2],
        [8, 9, 8],
        [2, 2, 4]])

In [ ]:
tensor_B = torch.randint(low=1, high=10, size=(5, 3))
tensor_B

tensor([[9, 5, 1],
        [2, 9, 8],
        [2, 9, 8],
        [4, 5, 7],
        [5, 1, 6]])

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**.

A **TRANSPOSE** switches the axes or dimension of a given tensor.

In [ ]:
tensor_A @ tensor_B.T

tensor([[ 35,  39,  39,  38,  34],
        [ 75,  48,  48,  52,  49],
        [125, 161, 161, 133,  97],
        [ 32,  54,  54,  46,  36]])

In [ ]:
# How the matrix multiplication operation works when tensor_B is transpose.

print(f'Original Shapes : tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}')
print(f'New Shapes : tensor_A = {tensor_A.shape} and tensor_B.T = {tensor_B.T.shape}')
print('Output : \n')
Output = tensor_A@tensor_B.T
print(Output)
print(f'\nOutput Shape = {Output.shape}')

Original Shapes : tensor_A = torch.Size([4, 3]) and tensor_B = torch.Size([5, 3])
New Shapes : tensor_A = torch.Size([4, 3]) and tensor_B.T = torch.Size([3, 5])
Output : 

tensor([[ 35,  39,  39,  38,  34],
        [ 75,  48,  48,  52,  49],
        [125, 161, 161, 133,  97],
        [ 32,  54,  54,  46,  36]])

Output Shape = torch.Size([4, 5])


### Tensor Aggregation (Min, Max, Sum etc)

In [ ]:
# Create a tensor
x = torch.arange(start=1, end=24, step=2)
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
# Min, Max, mean, sum
print(f'Minimum : {torch.min(x)}')
print(f'Maximum : {x.max()}')
print(f'Mean : {torch.mean(x, dtype=torch.float16)}')
print(f'sum : {x.sum()}')

Minimum : 1
Maximum : 23
Mean : 12.0
sum : 144


### Finding the positional min and max values

In [ ]:
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [ ]:
## Finding the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [ ]:
xX = torch.randint(low=0, high=10, size=(1, 10))
xX

tensor([[1, 0, 0, 5, 4, 9, 1, 7, 1, 7]])

In [ ]:
torch.argmax(x), x.argmax()

(tensor(11), tensor(11))

### Reshaping, Stacking, Squeezinf, and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Statcking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Remove all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way.


#### **Important Note :**

In [ ]:
# Add an extra dimension (Reshaping)
import torch
x = torch.arange(start=0, end=16, step=2)
x_reshaped = torch.reshape(input=x, shape=(1, 8))
x_reshaped, x, x_reshaped.shape, x.shape

(tensor([[ 0,  2,  4,  6,  8, 10, 12, 14]]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14]),
 torch.Size([1, 8]),
 torch.Size([8]))

In [ ]:
x.shape, x.ndim

(torch.Size([8]), 1)

In [ ]:
# Change the view
z = x.view(4, 2)
z, z.shape

(tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14]]),
 torch.Size([4, 2]))

In [ ]:
# Changing z changes x because a view of a tensor shares the same memory as the original tensor
z[1:2,1] = 3
print(f'View of x\n {z}\n\n Tensor x : {x}')

View of x
 tensor([[ 0,  2],
        [ 4,  3],
        [ 8, 10],
        [12, 14]])

 Tensor x : tensor([ 0,  2,  4,  3,  8, 10, 12, 14])


In [ ]:
# Stack tensors on top of each other

x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14]])

In [ ]:
# Squeeze and Unsqueeze - removes all the single dimension from the target tensor
print(f'Previous tensor :{x_reshaped}')
print(f'Previous tensor shape :{x_reshaped.shape}')

#Revoves extra dimension from a tensor
x_squeeze = torch.squeeze(input=x_reshaped, dim=0)
print(f'\nNew Tensor :{x_squeeze}')
print(f'Shape of New Tensor : {x_squeeze.shape}')

Previous tensor :tensor([[ 0,  2,  4,  3,  8, 10, 12, 14]])
Previous tensor shape :torch.Size([1, 8])

New Tensor :tensor([ 0,  2,  4,  3,  8, 10, 12, 14])
Shape of New Tensor : torch.Size([8])


In [ ]:
print(f'Squeeze tensor : {x_squeeze}')
print(f'Shape of Squeeze tensor :{x_squeeze.shape}')

#Add an extra dimension to the tensor
x_unsqueeze = torch.unsqueeze(input=x_squeeze, dim=0)
print(f'\nUnsqueeze Tensor :{x_unsqueeze}')
print(f'Shape of unsqueeze tensor : {x_unsqueeze.shape}')

Squeeze tensor : tensor([ 0,  2,  4,  3,  8, 10, 12, 14])
Shape of Squeeze tensor :torch.Size([8])

Unsqueeze Tensor :tensor([[ 0,  2,  4,  3,  8, 10, 12, 14]])
Shape of unsqueeze tensor : torch.Size([1, 8])


In [ ]:
# Permute ~ also called rearranging the order of axes values.

# Create a tesnor as an image shape (height, width, colour)

x_original = torch.rand(size=(224, 224, 3))
print(f'Original Shape : {x_original.shape}')  # Height * Weight * Colour

#permute the original tensor to rearrage the axis order.
x_permute = torch.permute(x_original, dims=(2, 0, 1)) # rearrange to 0>1, 1>2, 2>0
print(f'Permuted Shape : {x_permute.shape}')

Original Shape : torch.Size([224, 224, 3])
Permuted Shape : torch.Size([3, 224, 224])


In [ ]:
x_permute[0,0,0] = 666666
print(x_permute[0,0,0])
print(x_original[0,0,0])

tensor(666666.)
tensor(666666.)


**important Note**
Since permuting returns a iew(share the same data as the original), he values in the permuted tensor will be the same as the origincal and if you change the values in the view, it will change the value of the original.

In [ ]:
x_copy = x_permute
x_copy[0,0,0]

tensor(666666.)