<a href="https://colab.research.google.com/github/adnansherwani/Deep-Learning/blob/main/00__pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

*   Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
*   Documents:  https://pytorch.org/docs/stable/index.html

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
print(torch.__version__)

2.4.1+cu121


In [4]:
torch.cuda.is_available()

False

In [5]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors
  
  ### Creating Tensors

  PyTorch Tensors are created using torch.Tensor() - https://pytorch.org/docs/stable/tensors.html


In [6]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [7]:
scalar.ndim

0

In [8]:
# Getting the python tensor as int
scalar.item()

7

In [9]:
# Vector
vector = torch.tensor(data=[1, 2])
vector

tensor([1, 2])

In [10]:
vector.ndim

1

In [11]:
vector.shape

torch.Size([2])

In [12]:
MATRIX = torch.tensor(data=[[2,4],
                            [6,7]])
MATRIX

tensor([[2, 4],
        [6, 7]])

In [13]:
MATRIX.ndim

2

In [14]:
MATRIX[1]

tensor([6, 7])

In [15]:
MATRIX.shape

torch.Size([2, 2])

In [16]:
TENSOR = torch.tensor(data=[[[[9,4,6],
                             [4,7,4],
                             [8,4,7]],
                            [[3,5,6],
                            [5,7,9],
                            [1,8,0]]],
                            [[[2,4,5],
                             [4,5,6],
                             [6,7,5]],
                            [[3,4,6],
                             [3,5,6],
                             [5,3,4]]],
                            [[[1,4,5],
                             [4,7,6],
                             [9,7,4]],
                             [[3,5,7],
                              [6,8,3],
                              [7,7,5]]]])

In [17]:
TENSOR

tensor([[[[9, 4, 6],
          [4, 7, 4],
          [8, 4, 7]],

         [[3, 5, 6],
          [5, 7, 9],
          [1, 8, 0]]],


        [[[2, 4, 5],
          [4, 5, 6],
          [6, 7, 5]],

         [[3, 4, 6],
          [3, 5, 6],
          [5, 3, 4]]],


        [[[1, 4, 5],
          [4, 7, 6],
          [9, 7, 4]],

         [[3, 5, 7],
          [6, 8, 3],
          [7, 7, 5]]]])

In [18]:
TENSOR.ndim

4

In [19]:
TENSOR.shape

torch.Size([3, 2, 3, 3])

In [20]:
TENSOR[0][1][0][1]

tensor(5)

In [21]:
TENSOR_1 = torch.randint(low=0, high=9, size=(3,3,3,3,3))

In [22]:
TENSOR_1.item

<function Tensor.item>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they stary with a tensor full of random numbers and then adjust those randome number to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random number`

Torch Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [23]:
### Create a random tensor of size or shape (3,4)

rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.6592, 0.7243, 0.5242],
        [0.4279, 0.0952, 0.7942],
        [0.0175, 0.2016, 0.6146],
        [0.7749, 0.5586, 0.9582]])

In [24]:
rand_tensor.ndim

2

In [25]:
## Create a random tensor with similar shape to an image tensor

rand_image_s_tensor = torch.rand(size=(224, 224, 3)) ## height, width. color channels (RGB)
rand_image_s_tensor.shape, rand_image_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones tensors

In [26]:
# Create a tensor of all zeros & ones

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

### Create a range of tensors and tensors like

In [29]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1, dtype= None)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=rand_tensor[1][0])
ten_zeros

tensor(0.)

In [31]:
rand_tensor*ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor Data Types

**Note:** Tensor datatypes is one of the 3 big errors you'll face with Pytorch or datatypes.

  1. Tensors not right datatype.
  2. Tensors not right shape
  3. Tensors not on the right device

Tensor Datatypes: https://pytorch.org/docs/stable/tensors.html

Precision Computer science : https://dbpedia.org/page/Precision_(computer_science)

In [32]:
# float 32 tensor
float32_tensor = torch.tensor(data=[3.0, 6.0, 9.0],
                              dtype=None,    #what datatypes is the tensor (e.g float)
                              device=None,  # what device is the tensor on cpu or cuda
                              requires_grad=False)   #whether or not to track gradients
float32_tensor

tensor([3., 6., 9.])

In [33]:
float32_tensor.dtype

torch.float32

In [34]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [35]:
((float32_tensor * float16_tensor * float32_tensor) + float32_tensor / float16_tensor).shape

torch.Size([3])

### Getting Information from Tensor.

  1. Tensors not right datatype - use `tensor.dtype`
  2. Tensors not right shape - use `tensor.shape`
  3. Tensors not on the right device - use `tensor.device`



In [39]:
## Create random tensors.
some_tensors = torch.rand(size=(2,3,3), dtype=torch.float16, device='cpu')

In [40]:
# Details of some_random tensors.

print(some_tensors)
print(f"Datatype :{some_tensors.dtype}")
print(f"Shape :{some_tensors.shape}")
print(f"Device :{some_tensors.device}")


tensor([[[0.3687, 0.8940, 0.3794],
         [0.1831, 0.2158, 0.7266],
         [0.2812, 0.0054, 0.0293]],

        [[0.8105, 0.6509, 0.4297],
         [0.2471, 0.6411, 0.5884],
         [0.5947, 0.4023, 0.5513]]], dtype=torch.float16)
Datatype :torch.float16
Shape :torch.Size([2, 3, 3])
Device :cpu


### Manipulating Tensors (tensor operations)

Tensors operation includes:
 1. Addition
 2. Substraction
 3. Multiplication (element-wise)
 4.  Division
 5. Matrix Multiplication

In [41]:
# Create a tensor

tensor = torch.tensor(data=[2,4,6])
tensor + 3 #addition

tensor([5, 7, 9])

In [42]:
tensor * 10 # Mulitplication

tensor([20, 40, 60])

In [43]:
tensor - 10 # Subtractions

tensor([-8, -6, -4])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks & deep learning.

1. Element-wise
2. Matrix Multiplication (dot product)

More information: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**Note :** There are two main rules that performing matrix multiplication needs to satisfy:

1.   The **inner dimensions** must match:

  *   `(3, 2) * (3, 2)` won't work
  *   `(2, 3) * (3, 2)` will work
  *   `(3, 2) * (2, 3)` will work

2.   The resulting matrix has the shape of the **outer dimensions:**

  *   `(2, 3) * (3, 2)` -> shape `(2, 2)`
  *   `(3, 2) * (2, 3)` -> shape  `(3, 3)`


**Important :** For Matrix Multiplication, we have different alias for torch.matmul() such as
  1. torch.mm
  2. `@`







In [44]:
# Element wise multiplication

print(tensor*tensor)

tensor([ 4, 16, 36])


In [45]:
# Matrix Maultiplication

print(tensor, "*", tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])


In [47]:
torch.matmul(input=tensor, other=tensor)

tensor(56)

In [48]:
2*2 + 4*4+6*6

56

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(56)
CPU times: user 3.85 ms, sys: 0 ns, total: 3.85 ms
Wall time: 5.93 ms


In [52]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 638 µs, sys: 0 ns, total: 638 µs
Wall time: 419 µs


tensor(56)

### One of the most common errors in deep learning:  shape errors

In [56]:
# shapes for matrix multiplication

tensor_A  = torch.randint(low=1, high=10, size=(3, 2))
tensor_A

tensor([[3, 3],
        [1, 5],
        [5, 9]])

In [58]:
tensor_B = torch.randint(low=1, high=10, size=(3,2))
tensor_B

tensor([[4, 4],
        [4, 7],
        [2, 3]])

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**.

A **TRANSPOSE** switches the axes or dimension of a given tensor.

In [60]:
tensor_A @ tensor_B.T

tensor([[24, 33, 15],
        [24, 39, 17],
        [56, 83, 37]])