<a href="https://colab.research.google.com/github/adnansherwani/Deep-Learning/blob/main/00__pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

*   Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
*   Documents:  https://pytorch.org/docs/stable/index.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
torch.cuda.is_available()

False

In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors
  
  ### Creating Tensors

  PyTorch Tensors are created using torch.Tensor() - https://pytorch.org/docs/stable/tensors.html


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Getting the python tensor as int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor(data=[1, 2])
vector

tensor([1, 2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor(data=[[2,4],
                            [6,7]])
MATRIX

tensor([[2, 4],
        [6, 7]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([6, 7])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor(data=[[[[9,4,6],
                             [4,7,4],
                             [8,4,7]],
                            [[3,5,6],
                            [5,7,9],
                            [1,8,0]]],
                            [[[2,4,5],
                             [4,5,6],
                             [6,7,5]],
                            [[3,4,6],
                             [3,5,6],
                             [5,3,4]]],
                            [[[1,4,5],
                             [4,7,6],
                             [9,7,4]],
                             [[3,5,7],
                              [6,8,3],
                              [7,7,5]]]])

In [16]:
TENSOR

tensor([[[[9, 4, 6],
          [4, 7, 4],
          [8, 4, 7]],

         [[3, 5, 6],
          [5, 7, 9],
          [1, 8, 0]]],


        [[[2, 4, 5],
          [4, 5, 6],
          [6, 7, 5]],

         [[3, 4, 6],
          [3, 5, 6],
          [5, 3, 4]]],


        [[[1, 4, 5],
          [4, 7, 6],
          [9, 7, 4]],

         [[3, 5, 7],
          [6, 8, 3],
          [7, 7, 5]]]])

In [17]:
TENSOR.ndim

4

In [18]:
TENSOR.shape

torch.Size([3, 2, 3, 3])

In [19]:
TENSOR[0][1][0][1]

tensor(5)

In [20]:
TENSOR_1 = torch.randint(low=0, high=9, size=(3,3,3,3,3))

In [21]:
TENSOR_1.item

<function Tensor.item>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they stary with a tensor full of random numbers and then adjust those randome number to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random number`

Torch Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
### Create a random tensor of size or shape (3,4)

rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.1424, 0.6874, 0.8801],
        [0.3301, 0.7382, 0.3719],
        [0.6819, 0.1060, 0.0977],
        [0.9948, 0.3820, 0.3904]])

In [23]:
rand_tensor.ndim

2

In [24]:
## Create a random tensor with similar shape to an image tensor

rand_image_s_tensor = torch.rand(size=(224, 224, 3)) ## height, width. color channels (RGB)
rand_image_s_tensor.shape, rand_image_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones tensors

In [25]:
# Create a tensor of all zeros & ones

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Create a range of tensors and tensors like

In [28]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1, dtype= None)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=rand_tensor[1][0])
ten_zeros

tensor(0.)

In [30]:
rand_tensor*ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor Data Types

**Note:** Tensor datatypes is one of the 3 big errors you'll face with Pytorch or datatypes.

  1. Tensors not right datatype.
  2. Tensors not right shape
  3. Tensors not on the right device

Tensor Datatypes: https://pytorch.org/docs/stable/tensors.html

Precision Computer science : https://dbpedia.org/page/Precision_(computer_science)

In [31]:
# float 32 tensor
float32_tensor = torch.tensor(data=[3.0, 6.0, 9.0],
                              dtype=None,    #what datatypes is the tensor (e.g float)
                              device=None,  # what device is the tensor on cpu or cuda
                              requires_grad=False)   #whether or not to track gradients
float32_tensor

tensor([3., 6., 9.])

In [32]:
float32_tensor.dtype

torch.float32

In [33]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
((float32_tensor * float16_tensor * float32_tensor) + float32_tensor / float16_tensor).shape

torch.Size([3])

### Getting Information from Tensor.

  1. Tensors not right datatype - use `tensor.dtype`
  2. Tensors not right shape - use `tensor.shape`
  3. Tensors not on the right device - use `tensor.device`



In [35]:
## Create random tensors.
some_tensors = torch.rand(size=(2,3,3), dtype=torch.float16, device='cpu')

In [36]:
# Details of some_random tensors.

print(some_tensors)
print(f"Datatype :{some_tensors.dtype}")
print(f"Shape :{some_tensors.shape}")
print(f"Device :{some_tensors.device}")


tensor([[[0.1147, 0.9419, 0.8267],
         [0.8306, 0.9292, 0.9531],
         [0.2046, 0.8354, 0.2871]],

        [[0.6572, 0.2095, 0.9995],
         [0.3711, 0.7646, 0.1523],
         [0.0664, 0.6050, 0.0210]]], dtype=torch.float16)
Datatype :torch.float16
Shape :torch.Size([2, 3, 3])
Device :cpu


### Manipulating Tensors (tensor operations)

Tensors operation includes:
 1. Addition
 2. Substraction
 3. Multiplication (element-wise)
 4.  Division
 5. Matrix Multiplication

In [37]:
# Create a tensor

tensor = torch.tensor(data=[2,4,6])
tensor + 3 #addition

tensor([5, 7, 9])

In [38]:
tensor * 10 # Mulitplication

tensor([20, 40, 60])

In [39]:
tensor - 10 # Subtractions

tensor([-8, -6, -4])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks & deep learning.

1. Element-wise
2. Matrix Multiplication (dot product)

More information: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**Note :** There are two main rules that performing matrix multiplication needs to satisfy:

1.   The **inner dimensions** must match:

  *   `(3, 2) * (3, 2)` won't work
  *   `(2, 3) * (3, 2)` will work
  *   `(3, 2) * (2, 3)` will work

2.   The resulting matrix has the shape of the **outer dimensions:**

  *   `(2, 3) * (3, 2)` -> shape `(2, 2)`
  *   `(3, 2) * (2, 3)` -> shape  `(3, 3)`


**Important :** For Matrix Multiplication, we have different alias for torch.matmul() such as
  1. torch.mm
  2. `@`







In [40]:
# Element wise multiplication

print(tensor*tensor)

tensor([ 4, 16, 36])


In [41]:
# Matrix Maultiplication

print(tensor, "*", tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])


In [42]:
torch.matmul(input=tensor, other=tensor)

tensor(56)

In [43]:
2*2 + 4*4+6*6

56

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(56)
CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 2.77 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 71 µs, sys: 12 µs, total: 83 µs
Wall time: 88 µs


tensor(56)

### One of the most common errors in deep learning:  shape errors

In [49]:
# shapes for matrix multiplication

tensor_A  = torch.randint(low=1, high=10, size=(4, 3))
tensor_A

tensor([[3, 9, 8],
        [4, 3, 2],
        [1, 4, 6],
        [8, 3, 4]])

In [50]:
tensor_B = torch.randint(low=1, high=10, size=(5, 3))
tensor_B

tensor([[3, 1, 7],
        [9, 2, 7],
        [8, 8, 2],
        [5, 1, 9],
        [2, 9, 6]])

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**.

A **TRANSPOSE** switches the axes or dimension of a given tensor.

In [51]:
tensor_A @ tensor_B.T

tensor([[ 74, 101, 112,  96, 135],
        [ 29,  56,  60,  41,  47],
        [ 49,  59,  52,  63,  74],
        [ 55, 106,  96,  79,  67]])

In [52]:
# How the matrix multiplication operation works when tensor_B is transpose.

print(f'Original Shapes : tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}')
print(f'New Shapes : tensor_A = {tensor_A.shape} and tensor_B.T = {tensor_B.T.shape}')
print('Output : \n')
Output = tensor_A@tensor_B.T
print(Output)
print(f'\nOutput Shape = {Output.shape}')

Original Shapes : tensor_A = torch.Size([4, 3]) and tensor_B = torch.Size([5, 3])
New Shapes : tensor_A = torch.Size([4, 3]) and tensor_B.T = torch.Size([3, 5])
Output : 

tensor([[ 74, 101, 112,  96, 135],
        [ 29,  56,  60,  41,  47],
        [ 49,  59,  52,  63,  74],
        [ 55, 106,  96,  79,  67]])

Output Shape = torch.Size([4, 5])


### Tensor Aggregation (Min, Max, Sum etc)

In [108]:
# Create a tensor
x = torch.arange(start=1, end=24, step=2)
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [111]:
# Min, Max, mean, sum
print(f'Minimum : {torch.min(x)}')
print(f'Maximum : {x.max()}')
print(f'Mean : {torch.mean(x, dtype=torch.float16)}')
print(f'sum : {x.sum()}')

Minimum : 1
Maximum : 23
Mean : 12.0
sum : 144


### Finding the positional min and max values

In [112]:
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [113]:
## Finding the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [114]:
xX = torch.randint(low=0, high=10, size=(1, 10))
xX

tensor([[7, 8, 9, 6, 0, 2, 6, 1, 8, 5]])

In [91]:
torch.argmax(x), x.argmax()

(tensor(14), tensor(14))

### Reshaping, Stacking, Squeezinf, and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Statcking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Remove all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way.


#### **Important Note :**

In [121]:
# Add an extra dimension (Reshaping)
import torch
x = torch.arange(start=0, end=16, step=2)
x_reshaped = torch.reshape(input=x, shape=(1, 4, 2))
x_reshaped, x, x_reshaped.shape, x.shape

(tensor([[[ 0,  2],
          [ 4,  6],
          [ 8, 10],
          [12, 14]]]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14]),
 torch.Size([1, 4, 2]),
 torch.Size([8]))

In [116]:
x.shape, x.ndim

(torch.Size([8]), 1)

In [164]:
# Change the view
z = x.view(4, 2)
z, z.shape

(tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14]]),
 torch.Size([4, 2]))

In [175]:
# Changing z changes x because a view of a tensor shares the same memory as the original tensor
z[1:2,1] = 3
print(f'View of x\n {z}\n\n Tensor x : {x}')

View of x
 tensor([[ 0,  2],
        [ 4,  3],
        [ 8, 10],
        [12, 14]])

 Tensor x : tensor([ 0,  2,  4,  3,  8, 10, 12, 14])


In [182]:
# Stack tensors on top of each other

x_stack = torch.stack([x, x, x, x], dim=1)
x_stack

tensor([[ 0,  0,  0,  0],
        [ 2,  2,  2,  2],
        [ 4,  4,  4,  4],
        [ 3,  3,  3,  3],
        [ 8,  8,  8,  8],
        [10, 10, 10, 10],
        [12, 12, 12, 12],
        [14, 14, 14, 14]])

In [197]:
# Squeeze and Unsqueeze - removes all the single dimension from the target tensor

x_squeeze = torch.squeeze(input=x, dim=0)
x_squeeze

tensor([ 0,  2,  4,  3,  8, 10, 12, 14])

In [191]:
x_unsqueeze = torch.unsqueeze(input=x, dim=0)
x_unsqueeze, x

(tensor([[ 0,  2,  4,  3,  8, 10, 12, 14]]),
 tensor([ 0,  2,  4,  3,  8, 10, 12, 14]))