<a href="https://colab.research.google.com/github/adnansherwani/Deep-Learning/blob/main/00__pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals

*   Resource Notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/
*   Documents:  https://pytorch.org/docs/stable/index.html

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
print(torch.__version__)

2.4.1+cu121


In [3]:
torch.cuda.is_available()

True

In [4]:
!nvidia-smi

Mon Sep 30 13:43:43 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

## Introduction to tensors
  
  ### Creating Tensors

  PyTorch Tensors are created using torch.Tensor() - https://pytorch.org/docs/stable/tensors.html


In [5]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Getting the python tensor as int
scalar.item()

7

In [8]:
# Vector
vector = torch.tensor(data=[1, 2])
vector

tensor([1, 2])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
MATRIX = torch.tensor(data=[[2,4],
                            [6,7]])
MATRIX

tensor([[2, 4],
        [6, 7]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[1]

tensor([6, 7])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor(data=[[[[9,4,6],
                             [4,7,4],
                             [8,4,7]],
                            [[3,5,6],
                            [5,7,9],
                            [1,8,0]]],
                            [[[2,4,5],
                             [4,5,6],
                             [6,7,5]],
                            [[3,4,6],
                             [3,5,6],
                             [5,3,4]]],
                            [[[1,4,5],
                             [4,7,6],
                             [9,7,4]],
                             [[3,5,7],
                              [6,8,3],
                              [7,7,5]]]])

In [16]:
TENSOR

tensor([[[[9, 4, 6],
          [4, 7, 4],
          [8, 4, 7]],

         [[3, 5, 6],
          [5, 7, 9],
          [1, 8, 0]]],


        [[[2, 4, 5],
          [4, 5, 6],
          [6, 7, 5]],

         [[3, 4, 6],
          [3, 5, 6],
          [5, 3, 4]]],


        [[[1, 4, 5],
          [4, 7, 6],
          [9, 7, 4]],

         [[3, 5, 7],
          [6, 8, 3],
          [7, 7, 5]]]])

In [17]:
TENSOR.ndim

4

In [18]:
TENSOR.shape

torch.Size([3, 2, 3, 3])

In [19]:
TENSOR[0][1][0][1]

tensor(5)

In [20]:
TENSOR_1 = torch.randint(low=0, high=9, size=(3,3,3,3,3))

In [21]:
TENSOR_1.item

<function Tensor.item>

## Random Tensors

Random tensors are important because the way many neural networks learn is that they stary with a tensor full of random numbers and then adjust those randome number to better represent the data.

`Start with random numbers -> look at the data -> update random numbers -> look at the data -> update random number`

Torch Random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [22]:
### Create a random tensor of size or shape (3,4)

rand_tensor = torch.rand(4, 3)
rand_tensor

tensor([[0.1077, 0.6923, 0.9111],
        [0.8011, 0.0446, 0.6335],
        [0.0424, 0.9849, 0.2810],
        [0.8611, 0.6586, 0.6666]])

In [23]:
rand_tensor.ndim

2

In [24]:
## Create a random tensor with similar shape to an image tensor

rand_image_s_tensor = torch.rand(size=(224, 224, 3)) ## height, width. color channels (RGB)
rand_image_s_tensor.shape, rand_image_s_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#### Zeros and Ones tensors

In [25]:
# Create a tensor of all zeros & ones

zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype

torch.float32

### Create a range of tensors and tensors like

In [28]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=11, step=1, dtype= None)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=rand_tensor[1][0])
ten_zeros

tensor(0.)

In [30]:
rand_tensor*ten_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### Tensor Data Types

**Note:** Tensor datatypes is one of the 3 big errors you'll face with Pytorch or datatypes.

  1. Tensors not right datatype.
  2. Tensors not right shape
  3. Tensors not on the right device

Tensor Datatypes: https://pytorch.org/docs/stable/tensors.html

Precision Computer science : https://dbpedia.org/page/Precision_(computer_science)

In [31]:
# float 32 tensor
float32_tensor = torch.tensor(data=[3.0, 6.0, 9.0],
                              dtype=None,    #what datatypes is the tensor (e.g float)
                              device=None,  # what device is the tensor on cpu or cuda
                              requires_grad=False)   #whether or not to track gradients
float32_tensor

tensor([3., 6., 9.])

In [32]:
float32_tensor.dtype

torch.float32

In [33]:
float16_tensor = float32_tensor.type(torch.float16)
float16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [34]:
((float32_tensor * float16_tensor * float32_tensor) + float32_tensor / float16_tensor).shape

torch.Size([3])

### Getting Information from Tensor.

  1. Tensors not right datatype - use `tensor.dtype`
  2. Tensors not right shape - use `tensor.shape`
  3. Tensors not on the right device - use `tensor.device`



In [35]:
## Create random tensors.
some_tensors = torch.rand(size=(2,3,3), dtype=torch.float16, device='cpu')

In [36]:
# Details of some_random tensors.

print(some_tensors)
print(f"Datatype :{some_tensors.dtype}")
print(f"Shape :{some_tensors.shape}")
print(f"Device :{some_tensors.device}")


tensor([[[0.1270, 0.3501, 0.7656],
         [0.8369, 0.2026, 0.7026],
         [0.9019, 0.4858, 0.0640]],

        [[0.0400, 0.0542, 0.5610],
         [0.3774, 0.8262, 0.2383],
         [0.3174, 0.2275, 0.1069]]], dtype=torch.float16)
Datatype :torch.float16
Shape :torch.Size([2, 3, 3])
Device :cpu


### Manipulating Tensors (tensor operations)

Tensors operation includes:
 1. Addition
 2. Substraction
 3. Multiplication (element-wise)
 4.  Division
 5. Matrix Multiplication

In [37]:
# Create a tensor

tensor = torch.tensor(data=[2,4,6])
tensor + 3 #addition

tensor([5, 7, 9])

In [38]:
tensor * 10 # Mulitplication

tensor([20, 40, 60])

In [39]:
tensor - 10 # Subtractions

tensor([-8, -6, -4])


### Matrix Multiplication

Two main ways of performing multiplication in neural networks & deep learning.

1. Element-wise
2. Matrix Multiplication (dot product)

More information: https://www.mathsisfun.com/algebra/matrix-multiplying.html

**Note :** There are two main rules that performing matrix multiplication needs to satisfy:

1.   The **inner dimensions** must match:

  *   `(3, 2) * (3, 2)` won't work
  *   `(2, 3) * (3, 2)` will work
  *   `(3, 2) * (2, 3)` will work

2.   The resulting matrix has the shape of the **outer dimensions:**

  *   `(2, 3) * (3, 2)` -> shape `(2, 2)`
  *   `(3, 2) * (2, 3)` -> shape  `(3, 3)`


**Important :** For Matrix Multiplication, we have different alias for torch.matmul() such as
  1. torch.mm
  2. `@`







In [40]:
# Element wise multiplication

print(tensor*tensor)

tensor([ 4, 16, 36])


In [41]:
# Matrix Maultiplication

print(tensor, "*", tensor)

tensor([2, 4, 6]) * tensor([2, 4, 6])


In [42]:
torch.matmul(input=tensor, other=tensor)

tensor(56)

In [43]:
2*2 + 4*4+6*6

56

In [44]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i]*tensor[i]
print(value)

tensor(56)
CPU times: user 3.14 ms, sys: 836 µs, total: 3.97 ms
Wall time: 6.78 ms


In [45]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 0 ns, total: 34 µs
Wall time: 37.9 µs


tensor(56)

### One of the most common errors in deep learning:  shape errors

In [46]:
# shapes for matrix multiplication

tensor_A  = torch.randint(low=1, high=10, size=(4, 3))
tensor_A

tensor([[3, 4, 9],
        [1, 7, 4],
        [1, 7, 3],
        [2, 7, 1]])

In [47]:
tensor_B = torch.randint(low=1, high=10, size=(5, 3))
tensor_B

tensor([[1, 2, 9],
        [1, 8, 3],
        [2, 1, 7],
        [5, 2, 8],
        [8, 6, 2]])

To fix our tensor shape issues, we can manupulate the shape of one of our tensors using a **transpose**.

A **TRANSPOSE** switches the axes or dimension of a given tensor.

In [48]:
tensor_A @ tensor_B.T

tensor([[92, 62, 73, 95, 66],
        [51, 69, 37, 51, 58],
        [42, 66, 30, 43, 56],
        [25, 61, 18, 32, 60]])

In [49]:
# How the matrix multiplication operation works when tensor_B is transpose.

print(f'Original Shapes : tensor_A = {tensor_A.shape} and tensor_B = {tensor_B.shape}')
print(f'New Shapes : tensor_A = {tensor_A.shape} and tensor_B.T = {tensor_B.T.shape}')
print('Output : \n')
Output = tensor_A@tensor_B.T
print(Output)
print(f'\nOutput Shape = {Output.shape}')

Original Shapes : tensor_A = torch.Size([4, 3]) and tensor_B = torch.Size([5, 3])
New Shapes : tensor_A = torch.Size([4, 3]) and tensor_B.T = torch.Size([3, 5])
Output : 

tensor([[92, 62, 73, 95, 66],
        [51, 69, 37, 51, 58],
        [42, 66, 30, 43, 56],
        [25, 61, 18, 32, 60]])

Output Shape = torch.Size([4, 5])


### Tensor Aggregation (Min, Max, Sum etc)

In [50]:
# Create a tensor
x = torch.arange(start=1, end=24, step=2)
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [51]:
# Min, Max, mean, sum
print(f'Minimum : {torch.min(x)}')
print(f'Maximum : {x.max()}')
print(f'Mean : {torch.mean(x, dtype=torch.float16)}')
print(f'sum : {x.sum()}')

Minimum : 1
Maximum : 23
Mean : 12.0
sum : 144


### Finding the positional min and max values

In [52]:
x

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [53]:
## Finding the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where minimum value occurs
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [54]:
xX = torch.randint(low=0, high=10, size=(1, 10))
xX

tensor([[0, 2, 7, 9, 3, 4, 1, 7, 6, 2]])

In [55]:
torch.argmax(x), x.argmax()

(tensor(11), tensor(11))

### Reshaping, Stacking, Squeezinf, and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Statcking - Combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Remove all `1` dimensions from a tensor.
* Unsqueeze - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way.


#### **Important Note :**

In [56]:
# Add an extra dimension (Reshaping)
import torch
x = torch.arange(start=0, end=16, step=2)
x_reshaped = torch.reshape(input=x, shape=(1, 8))
x_reshaped, x, x_reshaped.shape, x.shape

(tensor([[ 0,  2,  4,  6,  8, 10, 12, 14]]),
 tensor([ 0,  2,  4,  6,  8, 10, 12, 14]),
 torch.Size([1, 8]),
 torch.Size([8]))

In [57]:
x.shape, x.ndim

(torch.Size([8]), 1)

In [58]:
# Change the view
z = x.view(4, 2)
z, z.shape

(tensor([[ 0,  2],
         [ 4,  6],
         [ 8, 10],
         [12, 14]]),
 torch.Size([4, 2]))

In [59]:
# Changing z changes x because a view of a tensor shares the same memory as the original tensor
z[1:2,1] = 3
print(f'View of x\n {z}\n\n Tensor x : {x}')

View of x
 tensor([[ 0,  2],
        [ 4,  3],
        [ 8, 10],
        [12, 14]])

 Tensor x : tensor([ 0,  2,  4,  3,  8, 10, 12, 14])


In [60]:
# Stack tensors on top of each other

x_stack = torch.stack([x, x, x, x], dim=0)
x_stack

tensor([[ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14],
        [ 0,  2,  4,  3,  8, 10, 12, 14]])

In [61]:
# Squeeze and Unsqueeze - removes all the single dimension from the target tensor
print(f'Previous tensor :{x_reshaped}')
print(f'Previous tensor shape :{x_reshaped.shape}')

#Revoves extra dimension from a tensor
x_squeeze = torch.squeeze(input=x_reshaped, dim=0)
print(f'\nNew Tensor :{x_squeeze}')
print(f'Shape of New Tensor : {x_squeeze.shape}')

Previous tensor :tensor([[ 0,  2,  4,  3,  8, 10, 12, 14]])
Previous tensor shape :torch.Size([1, 8])

New Tensor :tensor([ 0,  2,  4,  3,  8, 10, 12, 14])
Shape of New Tensor : torch.Size([8])


In [62]:
print(f'Squeeze tensor : {x_squeeze}')
print(f'Shape of Squeeze tensor :{x_squeeze.shape}')

#Add an extra dimension to the tensor
x_unsqueeze = torch.unsqueeze(input=x_squeeze, dim=0)
print(f'\nUnsqueeze Tensor :{x_unsqueeze}')
print(f'Shape of unsqueeze tensor : {x_unsqueeze.shape}')

Squeeze tensor : tensor([ 0,  2,  4,  3,  8, 10, 12, 14])
Shape of Squeeze tensor :torch.Size([8])

Unsqueeze Tensor :tensor([[ 0,  2,  4,  3,  8, 10, 12, 14]])
Shape of unsqueeze tensor : torch.Size([1, 8])


In [63]:
# Permute ~ also called rearranging the order of axes values.

# Create a tesnor as an image shape (height, width, colour)

x_original = torch.rand(size=(224, 224, 3))
print(f'Original Shape : {x_original.shape}')  # Height * Weight * Colour

#permute the original tensor to rearrage the axis order.
x_permute = torch.permute(x_original, dims=(2, 0, 1)) # rearrange to 0>1, 1>2, 2>0
print(f'Permuted Shape : {x_permute.shape}')

Original Shape : torch.Size([224, 224, 3])
Permuted Shape : torch.Size([3, 224, 224])


In [64]:
x_permute[0,0,0] = 666666
print(x_permute[0,0,0])
print(x_original[0,0,0])

tensor(666666.)
tensor(666666.)


**important Note**
Since permuting returns a iew(share the same data as the original), he values in the permuted tensor will be the same as the origincal and if you change the values in the view, it will change the value of the original.

In [65]:
x_copy = x_permute
x_copy[0,0,0]

tensor(666666.)

### Indexing (Selecting data from tensor)

Indexing in PyTorch is very similar to indexing in Python NumPy arrays

In [66]:
# Create a tensor
x_index = torch.arange(start=1, end=13).reshape(1, 4, 3)
x_index

tensor([[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12]]])

In [67]:
x_index.shape, x_index.ndim

(torch.Size([1, 4, 3]), 3)

In [68]:
x_index[0, 2:, 1:]

tensor([[ 8,  9],
        [11, 12]])

In [69]:
x_index[0, 1, 1]

tensor(5)

### PyTorch tensors and NumPy

Since NumPy is a popular python numerical computing library. PyTorch has a functionality to intract with it nicely.

The two main method you'll use for NumPy to PyTorch and visa versa are:

* `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
* `torch.Tensor.numpy()` - PyTorch tensor to NumPy array

In [70]:
# NumPy to PyTorch tensor
import torch
import numpy as np

ndarray = np.arange(start=1., stop=13.).reshape(4, 3)
ndarray, ndarray.shape, ndarray.ndim, ndarray.dtype

(array([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]]),
 (4, 3),
 2,
 dtype('float64'))

In [71]:
tensors = torch.from_numpy(ndarray)
tensors, tensors.shape, tensors.ndim, tensors.dtype

(tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]], dtype=torch.float64),
 torch.Size([4, 3]),
 2,
 torch.float64)

**Important Note**

By default, NumPy arrays are created with the datatype `float64` and if you convert it to a PyTorch tensor, it'll keep the same datatype (as above).

However, many PyTorch calculations default to using `float32`.

So if you want to convert your NumPy array (float64) -> PyTorch tensor (float64) -> PyTorch tensor (float32), you can use tensor = `torch.from_numpy(array).type(torch.float32)`.

Because we reassigned tensor above, if you change the tensor, the array stays the same.

In [72]:
# change the array, keep the tensor -> checking if converting causes view i.e., sharing the same original memory.

ndarray = ndarray + 1
ndarray, tensors

(array([[ 2.,  3.,  4.],
        [ 5.,  6.,  7.],
        [ 8.,  9., 10.],
        [11., 12., 13.]]),
 tensor([[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]], dtype=torch.float64))

In [73]:
tensors = tensor.type(torch.float16)

In [74]:
# Converting tensors to array
c_ndarray = torch.Tensor.numpy(tensors)
c_ndarray, c_ndarray.shape, c_ndarray.ndim, c_ndarray.dtype

(array([2., 4., 6.], dtype=float16), (3,), 1, dtype('float16'))

### Reproducibility (trying to take the random out of random)

As you learn more about neural networks and machine learning, you'll start to discover how much randomness plays a part.

Well, pseudorandomness that is. Because after all, as they're designed, a computer is fundamentally deterministic (each step is predictable) so the randomness they create are simulated randomness (though there is debate on this too, but since I'm not a computer scientist, I'll let you find out more yourself).

How does this relate to neural networks and deep learning then?

We've discussed neural networks start with random numbers to describe patterns in data (these numbers are poor descriptions) and try to improve those random numbers using tensor operations (and a few other things we haven't discussed yet) to better describe patterns in data.

In short:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where **reproducibility** comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

PyTorch Reproducibility : https://pytorch.org/docs/stable/notes/randomness.html
Random Seed : https://en.wikipedia.org/wiki/Random_seed

In [75]:
import torch
import random

# Set random seed
random_seed = 42
torch.manual_seed(seed=random_seed)
random_tensor_A = torch.rand(4, 3)

#reset random seed everytime a new rand() is called
torch.manual_seed(seed=random_seed)
random_tensor_B = torch.rand(4, 3)

print(f'\nTensor A :{random_tensor_A}\n')
print(f'\nTensor B :{random_tensor_B}\n')
print(f'Does Tensor A equal to Tensor B? (anywhere)')
random_tensor_A == random_tensor_B


Tensor A :tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])


Tensor B :tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009],
        [0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Does Tensor A equal to Tensor B? (anywhere)


tensor([[True, True, True],
        [True, True, True],
        [True, True, True],
        [True, True, True]])

## Running Tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch

### 1. Getting a GPU

1. Easiest - Use Google colab for a free GPU (Optins to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GP, check this post for more infomation about the options you have for a New GPUs - https://timdettmers.com/2023/01/30/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services that allow you to rent computers on the cloud and access them

For option 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation : https://pytorch.org/get-started/locally/

In [76]:
!nvidia-smi

Mon Sep 30 13:43:44 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   49C    P8              12W /  70W |      3MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Checking is the GPU acess in PyTorch

In [77]:
# Check for GPU access

torch.cuda.is_available()

True

In [83]:
# Setup device agnostic code
device = ""
if torch.cuda.is_available():
  device = "cuda"
else:
  device = "cpu"

print(f"Process type : {device}")
print(f'Number of device(s) : {torch.cuda.device_count()}')

Process type : cuda
Number of device(s) : 1


### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/model on the GPU is beacause using a GPU results in faster computations.

In [84]:
# Create a tensor

x = torch.arange(1, 10)
print(x, x.device)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]) cpu


In [94]:
# Move tensor to GPU (if available)
x_on_gpu = x.to(torch.device(device))
x_on_gpu, x_on_gpu.device

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], device='cuda:0'),
 device(type='cuda', index=0))

### 4. Moving tensors back to the CPU

If tensor is in GPU, we can't move to NumPy. To fix this issue, set it to device 'cpu'

In [93]:
x_on_cpu = x_on_gpu.cpu().numpy()
x_on_cpu, x_on_cpu.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int64'))