# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [21]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [22]:
import torch
import random

x = torch.arange(start = 1, end=50).reshape(7,7)
x, x.shape, x.ndim, x.dtype

(tensor([[ 1,  2,  3,  4,  5,  6,  7],
         [ 8,  9, 10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19, 20, 21],
         [22, 23, 24, 25, 26, 27, 28],
         [29, 30, 31, 32, 33, 34, 35],
         [36, 37, 38, 39, 40, 41, 42],
         [43, 44, 45, 46, 47, 48, 49]]),
 torch.Size([7, 7]),
 2,
 torch.int64)

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [23]:
y = torch.arange(start=0, end=14, step=2).reshape(1, 7)
y, y.shape, y.ndim, y.dtype, y.T, y.T.shape

(tensor([[ 0,  2,  4,  6,  8, 10, 12]]),
 torch.Size([1, 7]),
 2,
 torch.int64,
 tensor([[ 0],
         [ 2],
         [ 4],
         [ 6],
         [ 8],
         [10],
         [12]]),
 torch.Size([7, 1]))

In [20]:
%%time
print(x@y.T)

tensor([[ 224],
        [ 518],
        [ 812],
        [1106],
        [1400],
        [1694],
        [1988]])
CPU times: user 3.3 ms, sys: 91 µs, total: 3.39 ms
Wall time: 2.78 ms


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [24]:
# Set manual seed
random_seed = 0
torch.manual_seed(random_seed)
# Create two random tensors
x_random = torch.rand(size=(7,7))
print(x_random)

torch.manual_seed(random_seed)
y_random = torch.rand(size=(1,7))
print(y_random)
# Matrix multiply tensors
torch.mm(x_random, y_random.T)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])


tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [25]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [55]:
# Set random seed
torch.manual_seed(seed=1234)
# Check for access to GPU
device = ''
if torch.cuda.is_available():
  device = 'cuda'
else:
  device = 'cpu'
print(device)
# Create two random tensors on GPU
torch.manual_seed(seed=1234)
x = torch.rand(size=(2, 3), device=device)
torch.manual_seed(seed=1234)
y = torch.rand(size=(2, 3), device = device)
print(x, y, x.shape, y.shape, x.ndim, y.ndim, x.dtype, y.dtype, x.device, y.device)

cuda
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0') torch.Size([2, 3]) torch.Size([2, 3]) 2 2 torch.float32 torch.float32 cuda:0 cuda:0



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [56]:
# Perform matmul on tensor_A and tensor_B
z = x@y.T
print(z)
z.shape

tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


torch.Size([2, 2])

### 8. Find the maximum and minimum values of the output of 7.

In [49]:
# Find max
print(z.max())
# Find min
print(z.min())

tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [50]:
# Find arg max
print(z.argmax())
# Find arg min
print(z.argmin())

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [60]:
# Set seed
torch.manual_seed(seed=7)
# Create random tensor
x = torch.rand(size=(1, 1, 1, 10))
print(x)
# Remove single dimensions
y = torch.reshape(input=x, shape=(1, 10))
print(y)

z = torch.squeeze(input=x)
print(z)
# Print out tensors and their shapes
print(x.shape, y.shape, z.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
tensor([[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
torch.Size([1, 1, 1, 10]) torch.Size([1, 10]) torch.Size([10])
